# Use Node 20
FROM node:20.16.0

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app files
COPY . .

# Expose React dev port
EXPOSE 5173

# Start React app
CMD ["npm", "start"]